In [1]:
import numpy as np
from data import *
from network import *


In [2]:
%load_ext autoreload
%autoreload 2


In [22]:
datas = load_data()
train_data, train_label = data.shuffle(datas)
train_data

array([[221.        , 211.66666667, 212.        , ..., 121.        ,
        113.        , 105.        ],
       [168.33333333, 168.66666667, 173.        , ...,   8.33333333,
          5.        ,   8.        ],
       [ 27.33333333,  36.        ,  46.66666667, ...,  33.33333333,
         31.66666667,  29.66666667],
       ...,
       [ 86.66666667,  84.        ,  79.33333333, ...,  57.        ,
         54.66666667,  50.33333333],
       [ 59.        ,  61.66666667,  64.66666667, ...,   7.33333333,
          8.        ,   9.        ],
       [226.66666667, 226.33333333, 227.33333333, ...,  63.66666667,
         36.        ,  35.66666667]])

In [23]:
for i in range(len(train_data)):
	train_data[i] = min_max_normalize(train_data[i])[0]

In [24]:
train_data

array([[0.86666667, 0.83006536, 0.83137255, ..., 0.4745098 , 0.44313725,
        0.41176471],
       [0.69111425, 0.69252468, 0.71086037, ..., 0.01410437, 0.        ,
        0.01269394],
       [0.0304414 , 0.07001522, 0.11872146, ..., 0.05783866, 0.05022831,
        0.04109589],
       ...,
       [0.39888683, 0.38404453, 0.3580705 , ..., 0.23376623, 0.22077922,
        0.19666048],
       [0.2764613 , 0.28909953, 0.30331754, ..., 0.03159558, 0.03475513,
        0.03949447],
       [0.985     , 0.98333333, 0.98833333, ..., 0.17      , 0.03166667,
        0.03      ]])

In [16]:
X = datas[0]
for i in range(len(X)):
    X[i] = z_score_normalize(X[i])[0]
Y= datas[1]

#onehot encode
# for i in range(len(Y)):
#     Y[i] = onehot_encode(Y[i])

# Y = np.array(Y)

In [17]:
regressor.test((X,Y))

(11.51260231200997, 0.2098)

In [25]:
regressor = Network({'lr':0.0000008},activation=softmax,loss_func = multiclass_cross_entropy,out_dim=10)

In [42]:
folds = data.generate_k_fold_set((train_data,train_label))
for i in folds:
    print(regressor.test(i[1]))

(5000, 10)
(5000, 10)
[[ -0.          -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -10.81969142]
 [-10.81966645  -0.          -0.         ...  -0.          -0.
   -0.        ]
 ...
 [ -0.          -0.          -0.         ... -10.81970117  -0.
   -0.        ]
 [-10.81900069  -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.          -0.         ...  -0.          -0.
  -10.81976447]]
<class 'numpy.float64'>
(10.81976198731827, 0.1038)
(5000, 10)
(5000, 10)
[[ -0.          -0.          -0.         ...  -0.          -0.
  -10.81996363]
 [ -0.          -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.          -0.         ...  -0.          -0.
   -0.        ]
 ...
 [-10.81917941  -0.          -0.         ...  -0.          -0.
   -0.        ]
 [ -0.          -0.          -0.         ...  -0.          -0.
   -0.        ]
 [-10.81950726  -0.     

In [26]:
for i in range(100):
    print(regressor.train((train_data,train_label)))

multi
13.122363377404323
multi
13.122363063558911
multi
13.122362749742418
multi
13.122362435954866
multi
13.122362122196252
multi
13.122361808466586
multi
13.12236149476585
multi
13.122361181094055
multi
13.1223608674512
multi
13.12236055383728
multi
13.12236024025229
multi
13.122359926696255
multi
13.122359613169143
multi
13.122359299670984
multi
13.122358986201759
multi
13.122358672761472
multi
13.12235835935011
multi
13.122358045967706
multi
13.12235773261423
multi
13.122357419289695
multi
13.122357105994103
multi
13.122356792727453
multi
13.122356479489738
multi
13.122356166280957
multi
13.122355853101126
multi
13.122355539950224
multi
13.122355226828272


KeyboardInterrupt: 

In [ ]:
test_data

In [60]:
weights =regressor.weights
X = append_bias(X)
weights.shape,X.shape

((1025, 10), (50000, 1025))

In [61]:
softmax((X @ weights))

array([[2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06],
       [2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06],
       [2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06],
       ...,
       [2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06],
       [2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06],
       [2.e-06, 2.e-06, 2.e-06, ..., 2.e-06, 2.e-06, 2.e-06]])

In [62]:
#onehot encode
Y = Y.tolist()
for i in range(len(Y)):
    Y[i] = onehot_encode(Y[i])

Y = np.array(Y)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [63]:
(Y-softmax((X @ weights))).shape

(50000, 10)

In [64]:
X.shape

(50000, 1025)

In [73]:
X = np.random.rand(1,1024)
X

array([[0.27350714, 0.13668895, 0.15814215, ..., 0.85131471, 0.9709324 ,
        0.91502784]])

In [74]:
y = np.random.rand(1,10)
y

array([[0.70957806, 0.06782266, 0.5159435 , 0.18637622, 0.68912814,
        0.35994542, 0.90680569, 0.83403932, 0.34260234, 0.04830315]])

In [75]:
(X.T @ y).shape

(1024, 10)