In [1]:
%load_ext autoreload
%autoreload 2

In [10]:
import copy
import os, gzip
import yaml
import numpy as np
import pickle
import matplotlib.pyplot as plt
import pandas as pd
import constants
from util import *


def unpickle(file):
        with open(file, 'rb') as fo:
            dict = pickle.load(fo, encoding='bytes')
        return dict

cifar_path = os.path.join("./data", constants.cifar10_directory)

train_images = []
train_labels = []
val_images = []
val_labels = []
for i in range(1,constants.cifar10_trainBatchFiles+1):
    images_dict = unpickle(os.path.join(cifar_path, f"data_batch_{i}"))
    data = images_dict[b'data']
    label = images_dict[b'labels']
    train_labels.extend(label)
    train_images.extend(data)
train_images = np.array(train_images)
train_labels = np.array(train_labels).reshape((len(train_labels),-1))
train_images, train_labels, val_images, val_labels = createTrainValSplit(train_images,train_labels)

len(train_images),len(train_labels),len(val_images),len(val_labels)

train_normalized_images =  normalize_data(train_images)
train_one_hot_labels = one_hot_encoding(train_labels)
val_normalized_images = normalize_data(val_images) #TODO
val_one_hot_labels = one_hot_encoding(val_labels)


In [11]:
from neuralnet import *

In [12]:
model = Neuralnetwork(config=util.load_config("./configs/config_2b.yaml"))

In [13]:
test_data = train_normalized_images[:1000]
test_labels = train_one_hot_labels[:1000]


In [14]:
model.forward(test_data,test_labels)

(2.3027354607959367, 0.097)

In [15]:
model.loss(model.y,test_labels)

2.3027354607959367

In [16]:
model.backward(gradReqd=True)

In [17]:
X=np.array([[1,2,3]])

In [18]:
for i in range(10000):
    print(model.forward(test_data,test_labels))
    model.loss(model.y,test_labels)
    model.backward(gradReqd=True)

(2.302081869889287, 0.099)
(2.3008437561067696, 0.111)
(2.2990211398124365, 0.184)
(2.296420339594175, 0.197)
(2.29253275318155, 0.199)
(2.286461115608756, 0.195)
(2.2769140280409905, 0.181)
(2.26261130799895, 0.175)
(2.2438230365985725, 0.168)
(2.2257052640973787, 0.168)
(2.218572730527489, 0.169)
(2.2217928985908215, 0.173)
(2.2162610330835495, 0.184)
(2.2004095786143116, 0.209)
(2.182791201540385, 0.196)
(2.1631270316529525, 0.212)
(2.1428800187836297, 0.23)
(2.1236799100845287, 0.244)
(2.1043789891264253, 0.267)
(2.0821362917681987, 0.285)
(2.0544807968378183, 0.288)
(2.0240903717608956, 0.301)
(1.9977902219112635, 0.303)
(1.9754931873993327, 0.303)
(1.9505498724584984, 0.31)
(1.921718978655625, 0.323)
(1.8910950803694981, 0.339)
(1.8559599790915875, 0.359)
(1.816221349775043, 0.376)
(1.7777416583421988, 0.401)
(1.7431958619860872, 0.429)
(1.7099210043240816, 0.451)
(1.6753229570638892, 0.462)
(1.6388612110068714, 0.47)
(1.5994169641702705, 0.47)
(1.5566123277130983, 0.489)
(1.5135

KeyboardInterrupt: 

In [197]:
a = np.array([[np.nan],[np.nan],[np.nan],[np.nan]])

In [200]:
any(np.isnan(a))

True

In [332]:
a=np.random.rand(128,10)
a

array([[0.61078007, 0.28068322, 0.20699258, ..., 0.03672136, 0.10802575,
        0.33886065],
       [0.80258568, 0.57204864, 0.51266773, ..., 0.61706652, 0.11383839,
        0.34522314],
       [0.50741194, 0.87422252, 0.49354658, ..., 0.39457608, 0.42182818,
        0.41102108],
       ...,
       [0.21050694, 0.80902364, 0.14692192, ..., 0.484538  , 0.30241951,
        0.56340836],
       [0.80380489, 0.13714849, 0.58069908, ..., 0.48783432, 0.08227232,
        0.45958406],
       [0.30646347, 0.82238121, 0.05697873, ..., 0.66721234, 0.77704929,
        0.86220297]])

In [343]:
delta = np.random.rand(1,10)
delta

array([[0.39692328, 0.13271575, 0.56754085, 0.68946497, 0.8005867 ,
        0.20015024, 0.16748258, 0.10456784, 0.63643025, 0.70647573]])

In [348]:
new_delta = delta.dot(a.T)

In [347]:
x=np.random.rand(1,3073)

In [350]:
x.T.dot(new_delta).shape

(3073, 128)

In [2]:
import numpy as np

In [13]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[4,5,6]])

In [14]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36]])